Apps/My_Blogs/urls.py
import hashlib

from django.urls import path

# @JavicSoftCode
from .views import BlogListView, BlogsDetailView

app_name = 'blog'


def generate_slug(text):
  return hashlib.md5(text.encode()).hexdigest()[:64]  # Un hash corto


urlpatterns = [
  path(f'b/{generate_slug("blog_list")}/', BlogListView.as_view(), name='blog_list'),
  path(f'b/{generate_slug("blog_details")}/<int:blog_id>/', BlogsDetailView.as_view(), name='blog_details'),
]

Apps/My_Portfolio/urls.py
import hashlib

from django.urls import path

# @JavicSoftCode
from .views import PortfolioListView

app_name = 'portfolio'


def generate_slug(text):
  return hashlib.md5(text.encode()).hexdigest()[:64]  # Un hash corto


urlpatterns = [
  path(f'p/{generate_slug("my_portfolio")}/', PortfolioListView.as_view(), name='my_portfolio'),
]

My_Portfolio_/urls.py
import hashlib

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# @JavicSoftCode
from .views import HomeTemplateView


def generate_slug(text):
  return hashlib.md5(text.encode()).hexdigest()[:64]  # Un hash corto


urlpatterns = [
                path("admin/", admin.site.urls),
                path('', HomeTemplateView.as_view(), name='home'),
                path(f'b/{generate_slug("blog")}/', include('Apps.My_Blogs.urls', namespace='blog')),
                path(f'p/{generate_slug("portfolio")}/', include('Apps.My_Portfolio.urls', namespace='portfolio')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/My_Blogs/models.py
import datetime

from django.db import models


class Blog(models.Model):
  title = models.CharField(max_length=50)
  description = models.TextField()
  image = models.ImageField(upload_to='app_blog/images')
  date = models.DateField(default=datetime.date.today)

  def __str__(self) -> str:
    return self.title

Apps/My_Portfolio/models.py
from datetime import date

from django.db import models


class Portfolio(models.Model):
  title = models.CharField(max_length=50)
  description = models.CharField(max_length=250)
  image = models.ImageField(upload_to='app_portfolio/images')
  url = models.URLField(blank=True)
  date = models.DateField(default=date.today)

  def __str__(self) -> str:
    return self.title

Apps/My_Blogs/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

# @JavicSoftCode
from .models import Blog


class BlogListView(ListView):
  model = Blog
  template_name = 'app_my_blogs/my_blogs.html'
  context_object_name = 'blogs'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['total_blogs'] = self.get_queryset().count()
    context['title'] = 'My Blogs JSC'
    return context


class BlogsDetailView(DetailView):
  model = Blog
  template_name = "app_my_blogs/blog_details.html"
  context_object_name = "blog"

  def get_object(self, **kwargs):
    blog_id = self.kwargs.get('blog_id')
    return get_object_or_404(Blog, pk=blog_id)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = self.object.title
    return context

Apps/My_Portfolio/views.py
from django.views.generic import ListView

# @JavicSoftCode
from .models import Portfolio


class PortfolioListView(ListView):
  model = Portfolio
  template_name = 'app_my_portfolio/my_portfolio.html'
  context_object_name = 'projects'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['title'] = 'My Portfolio JSC'
    return context

My_Portfolio_/views.py
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
  template_name = 'home/home.html'

FrontEnd/templates/app_my_blogs/blog_details.html
{% extends 'home/home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}

<div>
    <div class="container">
        <h1 class="align-center">{{ blog.title }}</h1>
        <h2 class="my-2 h5 text-muted">{{ blog.date|date:'F jS Y' }}</h2>
         <br>
        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="img-fluid img-blog-datails">
    </div>
    <div class="my-4">
        {{ blog.description|safe }}
    </div>
</div>

{% endblock %}

FrontEnd/templates/app_my_blogs/my_blogs.html
{% extends 'home/home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}

<h1 class="fs-2">Blogs</h1>
<h3>Actualmente hay " {{ total_blogs }} "  Blog{{ total_blogs|pluralize }}</h3>

{% for blog in blogs %}
<div class="py-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid img-size" src="{{ blog.image.url }}" alt="{{ blog.title }}">
            </div>
            <div class="col-9">
                <h4>{{ blog.title }}</h4>
                <p>{{ blog.description|striptags|truncatechars:100 }}</p>
                <p>{{ blog.date|date:'M d Y'|upper }}</p>
                <a href="{% url 'blog:blog_details' blog.id %}">{{ blog.title }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

FrontEnd/templates/app_my_portfolio/my_portfolio.html
{% extends 'home/home.html' %}
{% block title %} {{ title }} {% endblock title %}
{% block content %}
{% load static %}

<div class="container">
    <header class="row bg-black">
        <div class="col-md-4 my-auto">
            <img src="{% static 'public/app_my_portfolio/JSC.jpeg' %}" alt="JSC" class="img-JSC"/>
            <h1 class="text-white">Javic Soft Code</h1>
        </div>

        <div class="col-md-8 my-auto p-0">
            <h2 align="left">¡Hola! 👋 Mi nombre es Javier</h2><br>

            <img align="right" height="200" style="border-radius: 8; margin-top: -70px; padding-left: 20px;"
                 src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXQ4dHQ2MDA4YWg3N281MGV0YXV0NDR3M3Z4Z3Zkb3duczFuazIwcyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qgQUggAC3Pfv687qPC/giphy.gif"
                 alt="JSC"/>

            <p class="justif-interlineado">¡Hola! Soy Javier, un estudiante en constante progreso de aprendizaje, por
                adquirir nuevos conocimientos, e
                desarrolado proyectos tanto como el Frontend y el Backend, proyectos tantos personales y academicos.</p>

            <div align="left" class="tech-logos justif-interlineado">
                <div class="logo-wrapper" title="HTML5">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" height="30"
                         alt="html5 logo"/>
                </div>
                <div class="logo-wrapper" title="CSS3">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" height="30"
                         alt="css3 logo"/>
                </div>
                <div class="logo-wrapper" title="JavaScript">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
                         height="30" alt="javascript logo"/>
                </div>
                <div class="logo-wrapper" title="Python">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg" height="30"
                         alt="python logo"/>
                </div>
                <div class="logo-wrapper" title="NPM">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg"
                         height="30"
                         alt="npm logo"/>
                </div>
                <div class="logo-wrapper" title="Node.js">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" height="30"
                         alt="nodejs logo"/>
                </div>
                <div class="logo-wrapper" title="Django">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg" height="30"
                         alt="django logo"/>
                </div>
                <div class="logo-wrapper" title="Express">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original-wordmark.svg"
                         height="30" alt="express logo" style="filter: brightness(0) invert(1);"/>
                </div>
                <div class="logo-wrapper" title="PostgreSQL">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
                         height="30" alt="postgresql logo"/>
                </div>
                <div class="logo-wrapper" title="Git">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" height="30"
                         alt="git logo"/>
                </div>
                <div class="logo-wrapper" title="GitHub">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" height="30"
                         alt="github logo" style="filter: brightness(0) invert(1);"/>
                </div>
                <div class="logo-wrapper" title="PyCharm">
                    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pycharm/pycharm-original.svg"
                         height="30"
                         alt="pycharm logo"/>
                </div>
            </div>
            <br>

            <h3>Tecnologías que he estudiado</h3>
            <ul class="justif-interlineado">
                <li><strong>Lenguajes:</strong> JavaScript, Python</li>
                <li><strong>Frameworks/Librerías:</strong> Node.js, Express, Django</li>
                <li><strong>Frontend:</strong> HTML5, CSS3, JavaScript (para el desarrollo web)</li>
                <li><strong>Backend:</strong> Node.JS, Django (para el lado del servidor)</li>
                <li><strong>Bases de datos:</strong> PostgreSQL</li>
                <li><strong>Herramientas:</strong> Git, GitHub, PyCharm</li>
                <li><strong>Paradigmas:</strong> Programación Orientada Objetos ( POO )</li>
                <li><strong>Otros:</strong> Electron (lo usé brevemente para el desarrollo de aplicaciones)</li>
            </ul>

            <h3>Habilidades</h3>
            <ul class="justif-interlineado">
                <li>Competente en JavaScript, Python, Node.js y Express para el desarrollo backend.</li>
                <li>Experiencia en el uso de Django y PostgreSQL para construir aplicaciones web robustas.</li>
                <li>Habilidad en el control de versiones con Git y en hospedar proyectos en GitHub.</li>
                <li>Familiarizado con el uso de PyCharm para el desarrollo en Python y Electron para aplicaciones de
                    escritorio.
                </li>
            </ul>

            <h3>Contáctame</h3>
            <div align="left">
                <a href="mailto:ing.javiersistem02ejqp@gmail.com" target="__blank">
                    <img src="https://img.shields.io/static/v1?message=Gmail&logo=gmail&label=&color=D14836&logoColor=white&labelColor=&style=for-the-badge"
                         height="35" alt="logo de gmail"/>
                </a>

                <a href="https://paypal.me/SistemJavic16?country.x=EC&locale.x=es_XC" target="__blank">
                    <img src="https://img.shields.io/static/v1?message=PayPal&logo=paypal&label=&color=00457C&logoColor=white&labelColor=&style=for-the-badge"
                         height="35" alt="logo de paypal"/>
                </a>
            </div>
        </div>
    </header>
</div>

<div class="row my-4 text-center">
    <h3>Mis Proyectos</h3>

    <p>Proyectos realizados por mi, con el fin de mejorar mis habilidades en el desarrollo web. <br>
        Si te gusta alguno de ellos, no dudes en contactar conmigo para trabajar juntos</p>

    {% for project in projects %}
    <div class="col-md-4 p-4 ">
        <div class="card bg-black card-project">

            <img src="{{ project.image.url }}" class="card-img-top img-size-portfolio" alt="{{ project.title }}"/>

            <div class="card-body ">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>

                {% if project.url %}
                <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm " target="__blank" rel="noreferrer">Visitar
                    el Proyecto</a>
                {% endif %}

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

FrontEnd/templates/components/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic text-black" href="/admin" target="__blank">Admin</a>
        <a class="navbar-brand fw-bold fst-italic" href="/">Home JSC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'blog:blog_list'%}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:my_portfolio'%}">Portfolio</a>
                </li> &nbsp;
                <li class="nav-item d-flex align-items-center">
                                        <a class="btn btn-primary btn-sm" href="{% static 'public/app_my_portfolio/CV-JSC.pdf' %}" target="_blank">Download
                                            CV</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

FrontEnd/templates/components/welcome.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/welcome.css' %}">

<div class="container-welcome">
    <div class="text">
        <h1>Bienvenido Por Visitar</h1>
        <p>Mi Portafolio Web</p>
        <p>Javic Soft Code</p>
    </div>
    <img src="{% static 'public/app_my_portfolio/portfolio.jpeg' %}" alt="Logo o imagen relacionada">
</div>

FrontEnd/templates/home/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home JSC{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'public/iconos/JavicSoftCode.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body class="text-light">
{% include '../components/navbar.html' %}
<div class="container p-4 font-family-home container-welcome">
    {% block content %}
    {% include '../components/welcome.html' %}
    {% endblock %}
</div>

</body>
</html>